server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_registration
    # driverClassName: org.h2.Driver
    username: postgres
    password: password
    jpa:
      # database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      hibernate:
        ddl-auto: validate
      show-sql: true